[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "orbit"
readme  = "README.md"

# TODO: Change your package specifications
# -----------------------------------------------------------------
title = "DRL for Active Semantic SLAM"
author = "Andrea Bravo i Forn"
maintainer = "Andrea Bravo i Forn"
maintainer_email = "andrebf6@gmail.com"
description="Train a DRL agent for exploration tasks in indoor environments, exploiting semantic information from a 3D scene graph"
repository = "https://github.com/andrebf6/orbit.DRL-for-Active-Semantic-SLAM"
keywords = ["DRL", "drone", "exploration", "Semantics", "orbit"]
# -----------------------------------------------------------------

[dependencies]
"omni.isaac.orbit" = {}
"omni.isaac.orbit_assets" = {}
"omni.isaac.orbit_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
# TODO: Change your package name
# -----------------------------------------------------------------
name = "orbit.DRL-for-Active-Semantic-SLAM"
# -----------------------------------------------------------------

[orbit_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"